name: PaddleSOT Guard Benchmark Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Get date
        id: get_date
        run: |
          DATE=$(date +'%Y%m%d')
          echo "DATE=${DATE}" >> $GITHUB_OUTPUT
      - name: Setup Just 📦
        uses: extractions/setup-just@v2
      - name: Install the latest version of uv 📦
        uses: astral-sh/setup-uv@v3
      - name: Install python 📦
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies 📦
        run: just upgrade
      - name: Run tests and benchmarks ✅
        env:
          DATE: ${{ steps.get_date.outputs.DATE }}
        run: |
          uv run pytest --benchmark-compare --benchmark-save=${DATE} --benchmark-histogram=histograms/${DATE}
      - name: Create Pull Request 📦
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🔧 chore: Update Benchmark Results(${{ steps.get_date.outputs.DATE }})"
          sign-commits: true
          branch: benchmark-${{ steps.get_date.outputs.DATE }}
          title: "🔧 chore: Update Benchmark Results(${{ steps.get_date.outputs.DATE }})"
          body: |
            🔧 Update Benchmark Results(${{ steps.get_date.outputs.DATE }})

            ![histogram](https://cdn.jsdelivr.net/gh/zrr1999/PaddleGuardBenchmark@benchmark-${{ steps.get_date.outputs.DATE }}/histograms/${{ steps.get_date.outputs.DATE }}.svg)

            - [Histogram with nice tooltips][2]
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
            [2]: https://cdn.jsdelivr.net/gh/zrr1999/PaddleGuardBenchmark@benchmark-${{ steps.get_date.outputs.DATE }}/histograms/${{ steps.get_date.outputs.DATE }}.svg
          draft: false
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
